train_file: 'data/MVSA_Single/train.json'
val_file: 'data/MVSA_Single/test.json'                
test_file: 'data/MVSA_Single/dev.json'
            
bert_config: 'configs/config_bert.json'
fusion_bert_config: 'configs/config_bert_fusion.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 32
distill: True
warm_up: False

temp: 0.07
alpha: 0.4
queue_size: 8192
momentum: 0.995

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02} #lr 1e-4 to 1e-5
schedular: {sched: cosine, lr: 2e-5', epochs: 30, min_lr: 2e-5, decay_rate: 1, warmup_lr: 2e-5, warmup_epochs: 20, cooldown_epochs: 0}







